# Generated by Django 6.0.3 on 2026-04-07 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receptionist', '0003_patient_gender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['appointment_date', 'start_time']},
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together=set(),
        ),
    ]
