# Generated by Django 6.0.3 on 2026-04-07 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0001_initial'),
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pharmacy.medicine'),
        ),
        migrations.AlterUniqueTogether(
            name='prescription',
            unique_together={('consultation', 'medicine')},
        ),
    ]
