# Generated by Django 6.0.3 on 2026-04-07 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='dosage',
        ),
        migrations.AddField(
            model_name='prescription',
            name='duration_days',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='prescription',
            name='frequency',
            field=models.CharField(default='1-0-1', max_length=5),
        ),
    ]
