# Generated by Django 6.0.3 on 2026-04-07 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('unit', models.CharField(help_text='e.g., mg, ml, tablet, bottle', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='PharmacyBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_dispensed', models.PositiveIntegerField(default=1)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('dispensed_at', models.DateTimeField(auto_now_add=True)),
                ('prescription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_bill', to='doctor.prescription')),
            ],
        ),
    ]
