# Generated by Django 6.0.3 on 2026-04-07 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='min_stock',
            field=models.PositiveIntegerField(default=10, help_text='Minimum stock needed before warning'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='unit',
            field=models.CharField(choices=[('mg', 'mg'), ('ml', 'ml')], default='mg', help_text='e.g., mg, ml', max_length=50),
        ),
    ]
